spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
          filters:
            - name: CircuitBreaker
            args:
              name: STUDENT-SERVICE
              fallbackuri: forward:/StudentServiceFalling

        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/DepartmentServiceFalling
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost